## NumPy Installation

run in terminal: 

`pip install numpy`

## Import NumPy 

In [1]:
import numpy as np

## NumPy version check

In [2]:
print(np.__version__)

2.5.0


## Main Topics
--- 
- array Creation 
- ndim, shape 
- indexing, slicing
- reshaping 
- array operations, vectorized math functions 
- broadcasting 
- random numbers 
- sorting, filtering, searching, unique values 
- missing values handling 
- file i/o 
- linear algebra module 

## NumPy Array Creation 
---

### all functions summarized
---

| Function | Purpose | Syntax | Example |
|----------|---------|--------|---------|
| `np.array()` | Create an array from a Python list, tuple, or nested list | `np.array(object)` | `np.array([1,2,3])` |
| `np.zeros()` | Create an array filled with `0` | `np.zeros(shape)` | `np.zeros((2,3))` |
| `np.ones()` | Create an array filled with `1` | `np.ones(shape)` | `np.ones((3,2))` |
| `np.empty()` | Create an uninitialized array (contains arbitrary values) | `np.empty(shape)` | `np.empty((2,2))` |
| `np.full()` | Create an array filled with a specified value | `np.full(shape, value)` | `np.full((2,3), 5)` |
| `np.arange()` | Create evenly spaced values using a step size | `np.arange(start, stop, step)` | `np.arange(0, 10, 2)` |
| `np.linspace()` | Create a specified number of evenly spaced values | `np.linspace(start, stop, num)` | `np.linspace(0, 1, 5)` |
| `np.eye()` | Create an identity-like matrix (can be rectangular) | `np.eye(rows, cols)` | `np.eye(3)` |
| `np.identity()` | Create a square identity matrix | `np.identity(n)` | `np.identity(4)` |
| `np.zeros_like()` | Create a zero-filled array with the same shape as another array | `np.zeros_like(array)` | `np.zeros_like(a)` |
| `np.ones_like()` | Create a one-filled array with the same shape as another array | `np.ones_like(array)` | `np.ones_like(a)` |
| `np.full_like()` | Create an array with the same shape as another array, filled with a specified value | `np.full_like(array, value)` | `np.full_like(a, 9)` |

### Difference between `eye()` and `identity()`
---


| `eye()` | `identity()` |
|---------|--------------| 
| `np.eye(rows, columns)` | `np.identity(n)` |
| can create **rectangular** matrices | only **square** matrices |
| identity-like matrices | identity matrices | 
| more flexible | simpler | 



### Difference between `arange()` and `linspace()`
---

| `arange()` | `linspace()` |
|----------|------------| 
| `np.arange(start, stop, step)` | `np.linspace(start, stop, num)` | 
| Specify step size	| Specify number of values |
| Stop excluded | Stop included (default) | 
| example: <br> np.arange(0, 10, 2) <br> (0, 2, 4, 6, 8) | example: <br> np.linspace(0, 10, 5) <br> (0., 2.5, 5., 7.5, 10.) |

### Examples of array creation 
---

In [3]:
# example
my_list = [1, 2, 3, 4]
arr = np.array(my_list)     

print(arr)
print(type(arr))


[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
# arange vs linspace: 
a = np.linspace(0, 10, 5) 
print(a) 

b = np.arange(0, 10, 2)
print(b) 

[ 0.   2.5  5.   7.5 10. ]
[0 2 4 6 8]


In [5]:
# eye vs identity: 
a = np.eye(2, 3) 
print(a) 

b = np.identity(5) 
print(b)

[[1. 0. 0.]
 [0. 1. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Numpy Random Number Generation

In [73]:
# numpy array with random values

rng = np.random.default_rng() # default rng 

rand_0 = rng.random(5, dtype=float) # specify dtype as float
rand_1 = rng.random(5) # when nothing is specified, dtype is float by default

print(f"rand_0: {rand_0}")
print(f"rand_1: {rand_1}")


rand_2 = rng.random((4,5)) # random floats between 0 and 1 in a 4x5 array

print(f"rand_2: {rand_2}")


# random array of integers

rand_3 = rng.integers(0, 10, size=5) # integers between 0 and 10

print(f"rand_3: {rand_3}")

# custom rng 

custom_rng = np.random.default_rng(seed=42) # set seed for reproducibility
rand_4 = custom_rng.random(5)

print(f"rand_4: {rand_4}")

# Normal distribution:

rand_5 = rng.normal(loc=0.0, scale=1.0, size=5) # mean=0, std=1

print(f"rand_5: {rand_5}")

rand_0: [0.53416607 0.65279868 0.28247094 0.02444606 0.38999114]
rand_1: [0.02537609 0.18817059 0.27201198 0.67224144 0.84284018]
rand_2: [[0.90252979 0.84590522 0.36095274 0.27749292 0.80945461]
 [0.08585954 0.00304078 0.18962918 0.66759427 0.72245192]
 [0.25426258 0.36667739 0.8882847  0.70821969 0.80022357]
 [0.58749625 0.24817326 0.81676769 0.91904399 0.79020322]]
rand_3: [6 6 1 7 3]
rand_4: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
rand_5: [ 0.23681703 -0.94153561 -0.71662492  0.5257006   0.07484692]


Why is `normal()` even needed? Because the `random()` function generates random numbers from a uniform distribution, while the `normal()` function generates random numbers from a normal (Gaussian) distribution. The normal distrbution is much faster than the classic Mersenne Twister algorithm (`mt19937`) used by the `random()` function.

## NumPy Array vs Python List
---

### difference table 
---

| Feature | Python List | NumPy Array |
|---------|-------------|-------------| 
| purpose | general use | numerical computation |
| speed | slower | much faster | 
| memory | more memory | less memory | 
| data types | all types | usually same type | 
| math operations | limited | powerful | 
| ML/Data analysis | rarely used | standard |

### Examples of list and arrays 
---

In [6]:
my_list = [1, 2, 3, 4] 
list_2 = [5, 4, 6, 7] 

my_array = np.array(my_list) 
array_2 = np.array(list_2)  

# addition 
print(my_list + list_2)     # list concatenation
print(my_array + array_2)   # elementwise addition 

# multiplication 
print(my_list * 2)  
print(my_array * 2)

[1, 2, 3, 4, 5, 4, 6, 7]
[ 6  6  9 11]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


## Why NumPy is useful? 
---

- store numerical data efficiently 
- perform mathematical operations easily 
- work with matrices and vectors 
- statistical calculations 
- fast processing of large datasets (implemented in C)

## Data Types in NumPy
---

| Data Type                 | Meaning        | Example         |
| ------------------------- | -------------- | --------------- |
| `int32`, `int64`          | Integer        | `1`, `25`       |
| `float32`, `float64`      | Decimal number | `3.14`          |
| `bool`                    | Boolean        | `True`, `False` |
| `complex64`, `complex128` | Complex number | `2+3j`          |
| `str_`                    | String         | `"Hello"`       |


| Operation                        | Syntax                      | Example                          | Output                          |
| -------------------------------- | --------------------------- | -------------------------------- | ------------------------------- |
| Check data type                  | `arr.dtype`                 | `np.array([1,2,3]).dtype`        | `dtype('int64')` *(or `int32`)* |
| Specify data type while creating | `np.array(data, dtype=...)` | `np.array([1,2,3], dtype=float)` | `array([1., 2., 3.])`           |
| Convert data type                | `arr.astype(type)`          | `arr.astype(float)`              | New array with float values     |


In [ ]:
arr_0 = np.array

## Array Dimensions 
---

In [7]:
arr_0 = np.array('A')
arr_1 = np.array(['A', 'B', 'C'])
arr_2 = np.array([
        ['A', 'B', 'C'], 
        ['D', 'E', 'F']
    ]) 
arr_3 = np.array([
    [
        ['A', 'B', 'C'], 
        ['D', 'E', 'F']
    ], 
    [
        ['G', 'H', 'I'], 
        ['J', 'K', 'L']]
    ])

# print the dimensions
print(arr_0.ndim)
print(arr_1.ndim)
print(arr_2.ndim)
print(arr_3.ndim)

0
1
2
3


## Array Shape  
--- 

**format:** 
- for 3d array: (layers, rows, columns) 
- for 2d array: (rows, columns) 
- number of elements in shape tuple = number of dimension of the array

In [8]:
arr_0 = np.array('A')
arr_1 = np.array(['A', 'B', 'C'])
arr_2 = np.array([
        ['A', 'B', 'C'], 
        ['D', 'E', 'F']
    ]) 
arr_3 = np.array([
    [
        ['A', 'B', 'C'], 
        ['D', 'E', 'F']
    ], 
    [
        ['G', 'H', 'I'], 
        ['J', 'K', 'L']]
    ])
                
# print the shapes 
# format: (layer, rows in each layer, columns in each rows)
print(arr_0.shape)
print(arr_1.shape)
print(arr_2.shape)
print(arr_3.shape)

()
(3,)
(2, 3)
(2, 2, 3)


## Array Indexing 
--- 

1. Chain Indexing 
1. Multidimensional Indexing 
<br> 

- one index for each axis/dimension 
- negative indexing is also possible

In [9]:
arr_0 = np.array('A')
arr_1 = np.array(['A', 'B', 'C'])
arr_2 = np.array([
        ['A', 'B', 'C'], 
        ['D', 'E', 'F']
    ]) 
arr_3 = np.array([
    [
        ['A', 'B', 'C'], 
        ['D', 'E', 'F']
    ], 
    [
        ['G', 'H', 'I'], 
        ['J', 'K', 'L']]
    ])

# chain indexing: 
print(arr_1[1])
print(arr_2[1][1])
print(arr_3[0][1][2]) 
print()

# multi-dimensional indexing: 
print(arr_1[1])
print(arr_2[1, 1])
print(arr_3[0, 1, 2])

B
E
F

B
E
F


- ndim answers "How many axes are there?"
- shape answers "How many items are along each axis?"
- Indexing answers "Which item on each axis do you want?"

## Array Slicing 
---

Syntax: 
- `arr[layer_slice, row_slice, column_slice]` for 3d 
- `arr[row_slice, column_slice]` for 2d 
- `arr[start:stop:step]` 
- stop is exclusive 


In [81]:
# define array: 
arr_3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                [[10, 11, 12], [13, 14, 15], [16, 17, 18]], 
                [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

print(arr_3.ndim)
print(arr_3.shape)

print('\n')

# create a 2d array from layer 0 of a 3d array:
arr_2 = arr_3[0, :, :].copy()   # for separate/deep copy 

# [layer, row, column] syntax
# 0 -> take the first layer
# first `:` means take all rows
# second `:` means take all columns

# print result, dimension, and shape:
print(arr_2) 
print(arr_2.ndim) 
print(arr_2.shape) 


print('\n')

arr_2 = arr_3[0, 2, :].copy()   # for separate/deep copy


# print result, dimension, and shape:
print(arr_2) 
print(arr_2.ndim) 
print(arr_2.shape) 

3
(3, 3, 3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


[7 8 9]
1
(3,)


### Important Concept: Slices are Views 
---

```python
a = np.array([1,2,3,4,5])
b = a[1:4]
```

**Now:**

```python
b[0] = 100
print(a)
```

**Output:**

```text
[1 100 3 4 5]
```

Original array changed too.

**Why?** \
Because slicing usually creates a view, not a completely new copy. 

\
**Making an Independent Copy**
```python
b = a[1:4].copy()
```
Now changes in b won't affect a.

In [11]:
# reverse rows
print(arr_2[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [12]:
# reverse columns 
print(arr_2[:, ::-1])

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [13]:
# take a portion 
print(arr_3, "\n")  # original
print(arr_3[0:2, 0, 1:])    # 0, 1th layer, 0th row, 1, 2th column

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 

[[ 2  3]
 [11 12]]


## Array Reshaping 
---

- Total number of elements must remain the same. 

| Function    | Purpose                          | Syntax               | Example             |
| ----------- | -------------------------------- | -------------------- | ------------------- |
| `reshape()` | Change shape                     | `arr.reshape(shape)` | `arr.reshape(2,3)`  |
| `flatten()` | Convert to 1D (copy)             | `arr.flatten()`      | `arr.flatten()`     |
| `ravel()`   | Convert to 1D (view if possible) | `arr.ravel()`        | `arr.ravel()`       |
| `resize()`  | Change shape in-place            | `arr.resize(shape)`  | `arr.resize((3,2))` |


In [14]:
# reshape(shape)  

arr = np.arange(1, 7) 
print("original:\n", arr, sep="") 
print("total elements:", arr.size, "\n")

a = arr.reshape(2, 3) 
print(a, "\n")

b = arr.reshape(3, -1)  # calculate other dimension automatically 
print(b, "\n") 

c = arr.reshape(-1, 1) 
print(c, "\n")


original:
[1 2 3 4 5 6]
total elements: 6 

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 



In [15]:
# flatten() 
arr = np.arange(1, 13) 

a = arr.reshape(3, -1) 
print(a, "\n") 

b = arr.flatten() 
print(b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Possible Confusions between reshape() and resize()
---

| `reshape()`              | `resize()`                 |
| ------------------------ | -------------------------- |
| Returns a new view/array | Changes the original array |
| Original unchanged       | Original modified          |
| Most commonly used       | Rarely used                |


## Array Operations 
---

### Scalar arithmetic operations:

In [16]:
# scalar arithmetic operations: 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + 5) 
print(arr1 - 5) 
print(arr1 * 5) 
print(arr1 / 5) 
print(arr1 // 5) 
print(arr1 % 5) 
print(arr1 ** 5) 

[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]
[0 0 0]
[1 2 3]
[  1  32 243]


### Basic arithmetic operations

In [17]:
# basic arithmetic operations: 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2) 
print(arr1 - arr2)
print(arr1 * arr2) 
print(arr1 / arr2) 
print(arr1 // arr2) 
print(arr1 ** arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[  1  32 729]


### Vectorized math functions

In [18]:
# constants:
print(np.pi) 
print(np.e)

3.141592653589793
2.718281828459045


In [19]:
# power functions: 
arr1 = np.array([1, 2, 3])

print(np.sqrt(arr1))
print(np.cbrt(arr1)) 
print(np.pow(arr1, 2)) 

[1.         1.41421356 1.73205081]
[1.         1.25992105 1.44224957]
[1 4 9]


In [20]:
# rounding functions: 
arr = np.array([-1.129, 2.089, 3.567])
print(np.round(arr, 2))
print(np.floor(arr))
print(np.ceil(arr)) 
print(np.abs(arr))

[-1.13  2.09  3.57]
[-2.  2.  3.]
[-1.  3.  4.]
[1.129 2.089 3.567]


In [21]:
# trigonometric: 
print(np.sin(np.pi/2))
print(np.tan(np.pi/4))

1.0
0.9999999999999999


In [22]:
# exponential: 
arr = [1, 2, 3]
print(np.exp(arr)) 

[ 2.71828183  7.3890561  20.08553692]


In [23]:
# logarithmic:
arr = [np.e, np.e**2, 1]
print(np.log(arr))

[1. 2. 0.]


# Comparison operators 

# Boolean Indexing / Masking

```python
marks = np.array([10, 30, 50, 68, 74, 90, 100, 41, 55, 83])
```

This creates

```python
[10, 30, 50, 68, 74, 90, 100, 41, 55, 83]
```

---

## Step 1: `marks >= 40`

This comparison is **vectorized**.

Instead of comparing a single number, NumPy compares **every element**.

```python
marks >= 40
```

becomes

```python
[
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True
]
```

because

```text
10  >= 40 → False
30  >= 40 → False
50  >= 40 → True
68  >= 40 → True
...
```

The result is itself a NumPy array:

```python
array([False, False, True, True, True, True, True, True, True, True])
```

---

## Step 2: `marks[marks >= 40]`

Now this Boolean array is used as an **index**.

Think of it as saying:

> Keep every element whose corresponding Boolean value is `True`.

```
marks:

10   30   50   68   74   90   100   41   55   83
 F    F    T    T    T    T     T    T    T    T
```

Everything with `True` is selected.

Result:

```python
array([50, 68, 74, 90, 100, 41, 55, 83])
```

So

```python
print("passed:", marks[marks >= 40])
```

prints

```text
passed: [ 50  68  74  90 100  41  55  83]
```

---

## Likewise

```python
marks < 40
```

produces

```python
[
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False
]
```

so

```python
marks[marks < 40]
```

returns

```python
array([10, 30])
```

---

## This one

```python
marks == 100
```

produces

```python
[
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False
]
```

Then

```python
marks[marks == 100]
```

returns

```python
array([100])
```

Notice something important:

It **doesn't return the number `100`**.

It returns a **NumPy array containing one element**.

Therefore

```python
type(marks[marks == 100])
```

is

```python
<class 'numpy.ndarray'>
```

not

```python
<class 'int'>
```

---

## Why doesn't it return just `100`?

Because Boolean indexing **always returns an array**.

Maybe there are

* 0 matches
* 1 match
* 5 matches
* 100 matches

NumPy keeps the return type consistent.

Examples:

```python
marks[marks > 95]
```

returns

```python
array([100])
```

---

```python
marks[marks > 150]
```

returns

```python
array([])
```

(an empty NumPy array)

---

```python
marks[marks > 60]
```

returns

```python
array([68, 74, 90, 100, 83])
```

---

This "masking" mechanism is used extensively in data science and machine learning because it lets you filter data without writing loops. For example:

```python
positive_numbers = arr[arr > 0]
non_missing = arr[~np.isnan(arr)]
even_numbers = arr[arr % 2 == 0]
```

Each expression creates a Boolean mask and then uses that mask to select only the desired elements.


In [24]:
marks = np.array([10, 30, 50, 68, 74, 90, 100, 41, 55, 83]) 
print("passed:", marks[marks >= 40]) 
print("failed:", marks[marks < 40]) 
print("type:", type(marks[marks == 100]))

passed: [ 50  68  74  90 100  41  55  83]
failed: [10 30]
type: <class 'numpy.ndarray'>


### Matrix Operations

In [25]:
m1 = np.array([[1, 2, 3], [4, 5, 6]]) 
m2 = np.array([[50, 80, 60, 70], [50, 60, 70 , 80], [-5, -15, -20, -15]])

print(m1.shape, m2.shape)

# matrix multiplication: 
ans = m1 @ m2
print(ans)
print(ans.shape)

# transposition: 
print(ans.transpose())

print(np.sort(ans))


(2, 3) (3, 4)
[[135 155 140 185]
 [420 530 470 590]]
(2, 4)
[[135 420]
 [155 530]
 [140 470]
 [185 590]]
[[135 140 155 185]
 [420 470 530 590]]


## Broadcasting 

Not the broadcasting in networks :3 It basically means you resize the smaller array to match the shape of the larger array so that you can perform element-wise operations.

| Concept            | Description                                                          |
| ------------------ | -------------------------------------------------------------------- |
| Broadcasting       | Automatic expansion of smaller arrays during element-wise operations |
| Compatibility Rule | - Dimensions must be equal <br> - or one of them must be `1`                  |
| Shape Comparison   | Compared from **right to left**                                      |
| Memory             | No actual copying of data                                            |
| Main Benefit       | Eliminates loops and enables fast vectorized operations              |


### Broadcasting Rules
---

- NumPy compares the shapes from **right to left**.
- Two dimensions are compatible if:
    - **They are equal**, or
    - **One of them is 1**

Otherwise, broadcasting fails

In [26]:
# scalar operation example: 

arr = np.array([1, 2, 3]) 
a = arr + 10    # 10 broadcasted to [10, 10, 10] (virtually)
print(a)

[11 12 13]


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
a = arr + 10    # 10 broadcasred to [[10, 10, 10], [10, 10, 10]] (virtually)
print(a)

[[11 12 13]
 [14 15 16]]


In [28]:
# two arrays, with compatible dimensions: 

a = np.array([10, 20, 30])  # can imagine shape = (1, 3)
b = np.array([[1], [2], [3]])   # shape = (3, 1) 

print(a.shape, b.shape)     # compatible 
print(a + b) 
print(a * b)    # this is not matrix multiplication!!



(3,) (3, 1)
[[11 21 31]
 [12 22 32]
 [13 23 33]]
[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [29]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  # (3, 3)
b = np.array([[1], [2], [3]])  # (3, 1) 

print(a.shape, b.shape) 
print(a + b)
print(a * b)


(3, 3) (3, 1)
[[11 21 31]
 [42 52 62]
 [73 83 93]]
[[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


## Aggregation Functions 
---
- sum 
- max 
- min 
- mean 
- standard deviation 
- variance 

In [30]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]) 

print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.std())
print(arr.var()) 
print(arr.argmax())     # index of max 
print(arr.argmin())     # index of min

450
90
10
50.0
25.81988897471611
666.6666666666666
8
0


In [31]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]) 

# row specific calculations: 
print(arr[0].sum())
print(arr[1].max())
print(arr[2].min())
print(arr[0:2].mean()) 
print(arr[1:].std()) 

# column specific calculations: 
print(arr[:, 0:2].var()) 
print(arr[:, 1:].argmax())      # index of max 
print(arr[:, 0::2].argmin())     # index of min

60
60
70
35.0
17.07825127659933
625.0
5
0


## Filtering 
---

In [32]:
ages = np.array([[21, 17, 82, 19, 20], [1, 66, 25, 8, 11], [20, 38, 32, 55, 16]]) 

kids = ages[ages < 18]
adults = ages[(ages >= 18) & (ages < 60)] 
seniors = ages[ages >= 60] 

print("kids:", kids)
print("adults:", adults)
print("seniors:", seniors) 
print(type(kids), kids.shape)

kids: [17  1  8 11 16]
adults: [21 19 20 25 20 38 32 55]
seniors: [82 66]
<class 'numpy.ndarray'> (5,)


In [33]:
# preserve shape using np.where(): 
# syntax: np.where(condition, array, fillvalue for False) 
ages = np.array([[21, 17, 82, 19, 20], [1, 66, 25, 8, 11], [20, 38, 32, 55, 16]]) 

k1 = np.where(ages < 18, ages, 0)    
k2 = np.where(ages < 18)

print(k1, k2, sep="\n")
print(type(k1))

[[ 0 17  0  0  0]
 [ 1  0  0  8 11]
 [ 0  0  0  0 16]]
(array([0, 1, 1, 1, 2]), array([1, 0, 3, 4, 4]))
<class 'numpy.ndarray'>


## Random Numbers 
---

### all random functions summarized
---

use `np.random` module. 


| functions | purpose | syntax | example |
|-----------|---------|--------|---------|
| `rand()` | random floats (0-1) | rand(shape) | a = np.random.rand(2, 3) | 
| `randint()` | random integers | randint(low, high, size) | np.random.randint(0, 101, size=(3, 4))|
| `choice()` | random sampling/selection | choice(arr, size) | np.random.choice([10, 20, 30, 40], size=(2, 2))|
| `shuffle()` | in-place array shuffling | shuffle(arr) | np.random.shuffle(arr) |
| `permutation()` | return a shuffled copy | permutation(arr) | new_arr = np.random.permutation(arr) |
| `seed()` | reproduce same result | seed(value) | np.random.shuffle(42) |
| `randn()` | standard normal numbers | randn(shape) | np.random.randn(2, 3) | 





### examples

In [34]:
# creat an array with random numbers between 1 to 100: 
arr = np.random.randint(low=1, high=101, size=(3, 4))   # high is exclusive 
print(arr) 

arr_1d = [10, 20, 30, 40, 50, 60]

# choose a 2X2 matrix with random numbers: 
# given array must be 1d
arr_choice = np.random.choice(arr_1d, size=(2, 2))   
print(arr_choice) 



[[10 98 54 48]
 [33 74 23 95]
 [80 99  4 59]]
[[10 30]
 [60 20]]


In [35]:
arr = np.random.randint(low=1, high=101, size=(3, 4))   # high is exclusive 
print(arr) 

# shuffle in-place: 
np.random.shuffle(arr)  # rows are shuffled only 
print(arr) 

# return a shuffled copy, keep the original array unchanged: 
new_arr = np.random.permutation(arr)
print(new_arr)

[[61 54 74 85]
 [98 34 49 50]
 [62 15 62 79]]
[[98 34 49 50]
 [62 15 62 79]
 [61 54 74 85]]
[[98 34 49 50]
 [61 54 74 85]
 [62 15 62 79]]


In [36]:
np.random.seed(42)      # use same seed value to produce same result always 

arr = np.random.rand(3, 3) 
print(arr)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


## Sorting 
---

| Function       | Purpose                                  | Syntax            | Example                  | Output                  |
| -------------- | ---------------------------------------- | ----------------- | ------------------------ | ----------------------- |
| `np.sort()`    | Return a sorted copy                     | `np.sort(arr)`    | `np.sort([3,1,2])`       | `[1 2 3]`               |
| `arr.sort()`   | Sort the original array in-place         | `arr.sort()`      | `arr.sort()`             | Original array modified |
| `np.argsort()` | Return indices that would sort the array | `np.argsort(arr)` | `np.argsort([30,10,20])` | `[1 2 0]`               |


In [37]:
a = np.array([20, 50, 10, 40, 30, 30]) 

print(np.argsort(a)) 

sorted_result = np.sort(a) 
print(sorted_result)
print(a)    # original us unchanged 

a.sort()    # in-place sorting
print(a)    

[2 0 5 4 3 1]
[10 20 30 30 40 50]
[20 50 10 40 30 30]
[10 20 30 30 40 50]


In [38]:
# 2d sorting 

arr = np.array([[-1, 6, -5, 4, 0, 10, 1], [99, 5, 8, 13, -2, 4, 2]]) 
print(np.sort(arr))     # row-wise sorting

[[-5 -1  0  1  4  6 10]
 [-2  2  4  5  8 13 99]]


## Searching 
---

| Function            | Purpose                                                  | Syntax                        | Example                          | Output            |
| ------------------- | -------------------------------------------------------- | ----------------------------- | -------------------------------- | ----------------- |
| `np.argmax()`       | Index of largest element                                 | `np.argmax(arr)`              | `np.argmax([3,8,2])`             | `1`               |
| `np.argmin()`       | Index of smallest element                                | `np.argmin(arr)`              | `np.argmin([3,8,2])`             | `2`               |
| `np.nonzero()`      | Indices of non-zero elements                             | `np.nonzero(arr)`             | `np.nonzero([0,5,0,2])`          | `(array([1,3]),)` |
| `np.searchsorted()` | Index where a value should be inserted in a sorted array | `np.searchsorted(arr, value)` | `np.searchsorted([10,20,30],25)` | `2`               |


In [39]:
arr = np.array([[-1, 6, -5, 4, 0, 10, 1], [99, 5, 8, 13, -2, 4, 2]]) 

print(np.argmax(arr))
print(np.argmin(arr))
print(np.nonzero(arr))
print(np.searchsorted(arr[0], 20))


7
2
(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]), array([0, 1, 2, 3, 5, 6, 0, 1, 2, 3, 4, 5, 6]))
7


## Unique and Counting Functions 
---

| Function                             | Purpose                                    | Syntax                               | Example                     | Output             |
| ------------------------------------ | ------------------------------------------ | ------------------------------------ | --------------------------- | ------------------ |
| `np.unique()`                        | Return unique values                       | `np.unique(arr)`                     | `np.unique([2,1,2,3])`      | `[1 2 3]`          |
| `np.unique(..., return_counts=True)` | Return unique values and their counts      | `np.unique(arr, return_counts=True)` | —                           | `(values, counts)` |
| `np.count_nonzero()`                 | Count non-zero values                      | `np.count_nonzero(arr)`              | `np.count_nonzero([1,0,2])` | `2`                |
| `np.bincount()`                      | Count occurrences of non-negative integers | `np.bincount(arr)`                   | `np.bincount([0,1,1,2])`    | `[1 2 1]`          |


In [40]:
# example: 

arr = np.array([[10, 20, 30, 0, -5], [10, 0, -10, 40, 20], [10, -20, -16, 40, 50]]) 

# unique values
print(np.unique(arr)) 

# unique values and their occurrence count 
unique_val, counts = np.unique_counts(arr)
print(unique_val)
print(counts)

# nonzero element count 
print(np.count_nonzero(arr)) 

# bincount works only with non-negative integers: 
a = np.arange(0, 11)
print(np.bincount(a))   # occurrence count of non-negative integers 


[-20 -16 -10  -5   0  10  20  30  40  50]
[-20 -16 -10  -5   0  10  20  30  40  50]
[1 1 1 1 2 3 2 1 2 1]
13
[1 1 1 1 1 1 1 1 1 1 1]


## Missing Values 
---

### NaN 
--- 

- NaN = not a number 
- use `np.nan`

### All NaN Functions
---

| Function       | Purpose                      | Syntax            | Output    |
| -------------- | ---------------------------- | ----------------- | -------------------------- |
| `np.isnan()`   | Check which values are `NaN` | `np.isnan(arr)`   | `[False False True False]` |
| `np.nanmean()` | Mean ignoring `NaN`          | `np.nanmean(arr)` |  `23.33`                    |
| `np.nansum()`  | Sum ignoring `NaN`           | `np.nansum(arr)`  |  `70`                       |
| `np.nanmax()`  | Maximum ignoring `NaN`       | `np.nanmax(arr)`  |  `40`                       |
| `np.nanmin()`  | Minimum ignoring `NaN`       | `np.nanmin(arr)`  |  `10`                       |


In [41]:
# example 

arr = np.array([[10, np.nan, 20], [np.nan, 30, 40], [50, 60, np.nan]])
print(arr) 

# print NaN status: 
print(np.isnan(arr)) 

# print sum ignoring nan: 
print(np.nansum(arr))

# print max ignoring nan: 
print(np.nanmax(arr)) 

# using sum() and max()
print(np.sum(arr))      # result = nan
print(np.max(arr))      # result = nan

[[10. nan 20.]
 [nan 30. 40.]
 [50. 60. nan]]
[[False  True False]
 [ True False False]
 [False False  True]]
210.0
60.0
nan
nan


## File Input/Output 
---

- NumPy arrays can be stored as files 
- filetypes: `.npy`, `.txt`, `.csv` 

### Important File I/O Functions 
---
| Function       | Purpose                                      | Syntax                      | Example                       |
| -------------- | -------------------------------------------- | --------------------------- | ----------------------------- |
| `np.save()`    | Save array in NumPy's binary format (`.npy`) | `np.save(filename, arr)`    | `np.save("data.npy", arr)`    |
| `np.load()`    | Load a `.npy` file                           | `np.load(filename)`         | `np.load("data.npy")`         |
| `np.savetxt()` | Save array as a text file (`.txt`, `.csv`)   | `np.savetxt(filename, arr)` | `np.savetxt("data.txt", arr)` |
| `np.loadtxt()` | Load data from a text file                   | `np.loadtxt(filename)`      | `np.loadtxt("data.txt")`      |


In [42]:
# example 
arr = np.arange(-10, 11, 1)
print(arr)  

# save as npy file 
np.save("my_data.npy", arr) 

# load from npy file 
a = np.load("my_data.npy") 
print(a)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]


In [43]:
# save as txt file 
arr = np.arange(-10, 11, 1) 
np.savetxt("my_arr.txt", arr) 
print("saved as text file successfully") 

# load text file 
a = np.loadtxt("my_arr.txt")
print(a) 

saved as text file successfully
[-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.   2.   3.
   4.   5.   6.   7.   8.   9.  10.]


In [44]:
# save as csv file 
arr = np.arange(-5, 6, 1)
np.savetxt("my_csv_arr.csv", arr, delimiter=",")
print("saved as csv file successfully") 

# load the csv file 
b = np.loadtxt("my_csv_arr.csv")
print(b)

saved as csv file successfully
[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]


## Linear Algebra Related 
--- 

### Topics 
--- 

use **`np.linalg` module** of NumPy. 

- Matrix multiplication
- Matrix inverse
- Determinant
- Rank
- Solving systems of equations
- Eigenvalues & Eigenvectors
- Matrix norms
- Matrix decomposition

### Matrix Multiplication 
--- 

| Function      | Purpose                             |
| ------------- | ----------------------------------- |
| `@`           | Matrix multiplication               |
| `np.matmul()` | Matrix multiplication               |
| `np.dot()`    | Dot product / Matrix multiplication |


In [45]:
# example of matrix multiplication 

a = np.arange(0, 9) 
a = a.reshape(3, -1) 

b = np.arange(-5, 4) 
b = b.reshape(3, -1) 

print(a @ b) 
print(np.matmul(a, b)) 
print(np.dot(a, b)) 

# vector (1d array) 
v = np.array([10, 20, 30]) 
print(v)

print(a @ v) 
print(np.matmul(v, a))
print(np.dot(a, v))

[[  0   3   6]
 [-18  -6   6]
 [-36 -15   6]]
[[  0   3   6]
 [-18  -6   6]
 [-36 -15   6]]
[[  0   3   6]
 [-18  -6   6]
 [-36 -15   6]]
[10 20 30]
[ 80 260 440]
[240 300 360]
[ 80 260 440]


### Transposition of Matrix 
--- 

| Function         | Purpose          |
| ---------------- | ---------------- |
| `.T`             | Transpose matrix |
| `np.transpose()` | Transpose matrix |


In [46]:
# example: 
a = np.array([[10, 20, 30], [40, 50, 60]])
print(a, a.shape)

b = a.T 
print(b, b.shape)

[[10 20 30]
 [40 50 60]] (2, 3)
[[10 40]
 [20 50]
 [30 60]] (3, 2)


### Matrix Inverse 
--- 

- matrix must be square 
- and determinant should be non-zero (non-singular matrix)
- use `np.linalg.inv(matrix)` function

In [47]:
# example 

a = np.array([[10, 20, 30], [400, -50, 60], [70, 80, 100]]) 

b = np.linalg.inv(a)
print(b)
print(np.round(a @ b))    # identity matrix 


[[-0.03904382  0.00159363  0.01075697]
 [-0.14262948 -0.00438247  0.04541833]
 [ 0.14143426  0.00239044 -0.03386454]]
[[ 1. -0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]


### Matrix Determinant 
--- 
- use `np.linalg.det()` function

In [48]:
# example: 

a = np.array([[10, 20, 30], [40, 50, 60], [-1, -5, 3]]) 
d = np.linalg.det(a)
print(d) 

# for singular matrix checking: 
print(np.isclose(d, 0))     # to avoid floating point precision issue, use isclose() instead of ==

-3599.999999999998
False


### Matrix Rank 
--- 

- rank = number of linearly independent rows in a matrix 
- rank $<=$ min(m, n)
    - m = number of rows  
    - n = number of columns 
- use `np.linalg.matrix_rank(A)` function

In [49]:
# example: 
a = np.array([[10, 20], [30, 60], [50, 80]]) 
print(np.linalg.matrix_rank(a))

2


### Matrix Trace
--- 
- Trace = sum of entries along main diagonal 
- use `np.linalg.trace(A)` function

In [50]:
# example: 
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
b = a[:, 0:2] 

t1 = np.linalg.trace(a)
t2 = np.linalg.trace(b)
print(a, b, sep="\n")
print(t1, t2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 20]
 [40 50]
 [70 80]]
150 60


### Solving Linear System 
--- 

- linear system = set of linear equations 
- Ax = b 
    - A = coefficient matrix 
    - x = variable matrix/vector 
    - b = constant vector 
- use `np.linalg.solve(A, b)` function 

In [51]:
# example 

A = np.array([[1, 1], [2, 1]]) 
b = np.array([5, 8]) 

x = np.linalg.solve(A, b) 
print(x) 


[3. 2.]


### Norm 
--- 

| Function                        | Purpose                                    | Example                         |
| ------------------------------- | ------------------------------------------ | ------------------------------- |
| `np.linalg.norm(v)`             | L2 norm (vector) / Frobenius norm (matrix) | `np.linalg.norm(v)`             |
| `np.linalg.norm(v, ord=1)`      | L1 norm                                    | `np.linalg.norm(v, ord=1)`      |
| `np.linalg.norm(v, ord=2)`      | L2 norm                                    | `np.linalg.norm(v, ord=2)`      |
| `np.linalg.norm(v, ord=np.inf)` | Infinity norm                              | `np.linalg.norm(v, ord=np.inf)` |


| Norm | Meaning | Formula | Common Use |
|----- | ------- | ------- | -----------| 
| **L1 Norm** | Sum of absolute values | $$\sum{\|x_i\|}$$ | Lasso Regression, feature selection |
| **L2 Norm** | Euclidean length | $$\sqrt{\sum{x_i^2}}$$ | Most common, Ridge Regression | 
| **Infinity Norm** | Largest absolute value | max($\|x_i\|$) |  Maximum magnitude |


In [52]:
# example:
arr = np.array([1, -4, 5, 2, 0, -7, 3]) 

print(np.linalg.norm(arr))  # L2 norm by default 
print(np.linalg.norm(arr, ord = 1)) # L1 norm 
print(np.linalg.norm(arr, ord = np.inf)) # infinity norm 


10.198039027185569
22.0
7.0


### Eigenvalue and Eigenvector
---

- eigenvector = for a **square matrix** A, an eigenvector is a non-zero vector, whose **direction doesn't change** after multiplication by A. 
- it only **scales the magnitude**. 
- the scaling factor is called eigenvalue 
- mathematically: $$Av = \lambda v$$
    - A = matrix 
    - $v$ = Eigenvector of A 
    - $\lambda$ = Eigenvalue of A corresponding to $v$

| Function              | Purpose                              | Syntax                 | Example                              |
| --------------------- | ------------------------------------ | ---------------------- | ------------------------------------ |
| `np.linalg.eig()`     | Compute eigenvalues and eigenvectors | `np.linalg.eig(A)`     | `values, vectors = np.linalg.eig(A)` |
| `np.linalg.eigvals()` | Compute only eigenvalues             | `np.linalg.eigvals(A)` | `np.linalg.eigvals(A)`               |


In [53]:
# example: 

A = np.array([[4, 2], [1, 3]]) 

values, vectors = np.linalg.eig(A)
print(values, vectors, sep="\n") 

# just eigenvalues 
val = np.linalg.eigvals(A)
print(val)

[5.+0.j 2.+0.j]
[[ 0.89442719+0.j -0.70710678+0.j]
 [ 0.4472136 +0.j  0.70710678+0.j]]
[5.+0.j 2.+0.j]


### Matrix Decomposition 
--- 

| Decomposition | Function               | Formula           | Main Use                         |
| ------------- | ---------------------- | ----------------- | -------------------------------- |
| **SVD**       | `np.linalg.svd()`      | $A = U\Sigma V^T$ | PCA, Dimensionality Reduction    | 
| **QR**        | `np.linalg.qr()`       | $A = QR$          | Least Squares, Orthogonalization | 
| **Cholesky**  | `np.linalg.cholesky()` | $A = LL^T$        | Positive Definite Matrices       | 

<br> 

> Note: NumPy does not provide LU decomposition. It is available in SciPy (`scipy.linalg.lu()`)


In [54]:
# example 

A = np.array([[1, 2], [3, 4]]) 

U, S, VT = np.linalg.svd(A) 
print(U, S, VT, sep="\n") 

Q, R = np.linalg.qr(A) 
print(Q, R, sep="\n") 


[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
[5.4649857  0.36596619]
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]
